### ISSUE TITLE
Function: get_synthesizer_and_voice()

### ISSUE THREAD

**Issue by cclauss** [cvpe/Pythonista-scripts#23]
In the braille app, would it be possible to compartmentalize a lot of objc boilerplate by creating a function of the form:
```python
from typing import Tuple


def get_synthesizer_and_voice(language: str = 'ja-JP') -> Tuple[ObjCInstance, ObjCInstance]:
```

**Comment by cvpe** [comment]
you must have noticed that I remain a novice with regard to Python.  Honestly, I have never heard of boilerplate and even the typing module.  I am a little ashamed but we will put it on my old age.  In 40 years, I have developed in maybe 10 programming languages, especially on main frame, and I recognize that when I discovered Pythonista, I did not have the courage to learn Python and I discovered  the little that I know by doing personal projects...
I'll try to understand your proposal

PS I don't forget the other one "Add automated testing using Travis CI and flake8", I'll process in a close future, promised

**Comment by cclauss** [comment]
These are just my ways of keeping you on your toes... It is fun learning all the ins and outs of Python.

**Comment by cvpe** [comment]
I understand and thank you but I can't promise that I shall not do the same error in the future...

PS in this case, I know that I knew that clipboard.get() returns a str and I use startwith in other cases, thus I'm unforgivable

**Comment by cclauss** [comment]
We are all imperfect and we all make mistakes over and over again which is why pair programming and code reviews are so powerful.  Linus Torvalds most famously said “Many eyes make all bugs small”.

**Comment by cvpe** [comment]
I know that...
I've programmed, at IBM, during 40 years in a lot of scientific, graphic, technical and engineering domains.
At the end, I was called "Mr  Bugs"  because I wrote the the biggest number of bugs per day, but it was not a negative surname because I also wrote the biggest number of statements per day 😀

**Comment by cvpe** [comment]
Could you please give me another example, because in this case, synthesizer has not to be returned but is created at begin of program.

**Comment by cclauss** [comment]
__voice__ is used on line 874 and __synthesizer__ is used on line 876 so as long as __get_synthesizer_and_voice()__ is called before line 874 is run for the first time then we should be OK.

**Comment by cvpe** [comment]
Yes, I know thanks. I just wanted to say that these variables never change thus..

Thus, before I use this feature, please give me another example. Thanks

**Comment by cclauss** [comment]
Building for reusablity means that __get_synthesizer_and_voice('fr-BE')__ !.__get_synthesizer_and_voice('ja-JP')__

**Comment by cvpe** [comment]
Done like:

..... def
def get_synthesizer_and_voice(language: str = 'ja-JP') -> Tuple(ObjCInstance, ObjCInstance):
	synthesizer=AVSpeechSynthesizer.new()
	voice_idx = -1
	for i, voice in enumerate(voices):
		#print(i,voice,voice.description())
		if 'ja-JP' in str(voice.description()):
			#print(voices[voice_jp].description())
			voice_idx = i
			break
	return synthesizer,voice_idx

......usage
		synthesizer, voice_jp = get_synthesizer_and_voice()
		if voice_jp < 0:
			return					# voice not found
		utterance.voice = voices[voice_jp]
		utterance.useCompactVoice = False 
		synthesizer.speakUtterance_(utterance)

Is it ok?
Thanks for your advices

**Comment by cvpe** [comment]
Need help....

Traceback (most recent call last):
  File "/var/mobile/Containers/Shared/AppGroup/668A7D98-7216-47ED-917D-AA0B6173167E/Pythonista3/Documents/MesTools/keyboards/Japanese Braille Input.py", line 154, in <module>
    def get_synthesizer_and_voice(language: str = 'ja-JP') -> Tuple(ObjCInstance, ObjCInstance):
  File "/var/containers/Bundle/Application/D77C1333-B4DC-46E7-97AF-3112F46BF951/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/typing.py", line 1282, in __new__
    raise TypeError("Type Tuple cannot be instantiated; "
TypeError: Type Tuple cannot be instantiated; use tuple() instead

**Comment by cvpe** [comment]
Is that not -> Tuple[ObjCInstance, ObjCInstance]:

Need help....

Traceback (most recent call last):
 File "/var/mobile/Containers/Shared/AppGroup/668A7D98-7216-47ED-917D-AA0B6173167E/Pythonista3/Documents/MesTools/keyboards/Japanese Braille Input.py", line 154, in <module>
   def get_synthesizer_and_voice(language: str = 'ja-JP') -> Tuple(ObjCInstance, ObjCInstance):
 File "/var/containers/Bundle/Application/D77C1333-B4DC-46E7-97AF-3112F46BF951/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/typing.py", line 1282, in __new__
   raise TypeError("Type Tuple cannot be instantiated; "
TypeError: Type Tuple cannot be instantiated; use tuple() instead

**Comment by cclauss** [comment]
Return the voice, not the index of the voice.

**Comment by cvpe** [comment]
Ok but if the function is called with an erroneous language, I have to return something as None and also check after call

**Comment by cclauss** [comment]
Raise an exception and return an English voice.
