### ISSUE TITLE
Could hide(True, field_names) method be created to reduce duplication?

### ISSUE THREAD

**Issue by cclauss** [cvpe/Pythonista-scripts#26]
```python
def hide_buttons(self, hide: bool = True, button_names: str = "") ->  None:
    button_names = button_names or "kanjis kanjis_up kanjis_ok kanjis_down kanjis_other"
    for button_name in button_names.split():
        self.[button_name].hidden = hide
```
This could simplify the code around lines 704-708 and 892-896 but where else could it be used and how?

**Comment by cvpe** [comment]
I'll do it but one question:
Can I define the function with additional parameter self?
def hide_buttons(self, hide: bool = True, button_names: str = "") --> None:

**Comment by cclauss** [comment]
You are correct.  We want a method (with self), not a function.

**Comment by cvpe** [comment]
Sorry, 
1) is it not missing for in "button_name in button_names:"?
2) why field_names instead of button_names?

**Comment by cvpe** [comment]
Sorry, 
1) is it not missing for in "button_name in button_names:"?
2) why field_names instead of button_names?
3) -> instead of -->
4) . too much in self.[button_name]

**Comment by cvpe** [comment]
Done in the future version, at two places you indicate (hide=True) + another one (hide=False)

**Comment by cclauss** [comment]
Nice.  Long train ride this afternoon... Time to hack ;-)

**Comment by cvpe** [comment]
Have a good trip

BBQ this afternoon with my smala, no time to jack 😥
