### ISSUE TITLE
Python syntax error in AddAfterAlarmToEvent.py

### ISSUE THREAD

**Issue by cclauss** [cvpe/Pythonista-scripts#29]
https://travis-ci.com/cvpe/Pythonista-scripts/jobs/207806129#L461
```
./AddAfterAlarmToEvent.py:54:17: E999 SyntaxError: invalid syntax
		titlbl.width = 
                ^
```

**Comment by cvpe** [comment]
Very strange, my local Pythonista code shows 
		titlbl.width = w - end_button.width - dat_button.width - 3*10

**Comment by cvpe** [comment]
Corrected 
Thanks

**Comment by cclauss** [comment]
Your change did not quite fix that file https://travis-ci.com/cvpe/Pythonista-scripts

**Comment by cvpe** [comment]
Wha! This is not automatic?
I told you I did not understand really how this Travis works 😢 and that I feel too stupid

**Comment by cvpe** [comment]
I restarted the build, is that the way?

**Comment by cclauss** [comment]
It is automatic and you can always find the “current build” at https://travis-ci.com/cvpe/Pythonista-scripts  Every time that you make a change to the code in the repo or I make a pull request, Travis CI will kickoff a new build.

Flake8 will stop at the first syntax error that it finds in each file so sometimes you fix one syntax error and then it finds another further down in the same file.

**Comment by cvpe** [comment]
"I told you I did not understand really how this Travis works 😢 and that I feel too stupid" was only a tentative of humor. I need to do that always, perhaps to hide my limits 😢, then don't never take me as serious.
