### ISSUE TITLE
Old style print in ./IdentifyAlbumOfPhotos.py

### ISSUE THREAD

**Issue by cclauss** [cvpe/Pythonista-scripts#31]
Just a few more files to work on and then the Travis ❌ will because a ✅ — I promise.

```
./IdentifyAlbumOfPhotos.py:35:15: E999 SyntaxError: invalid syntax
	print fn_index
              ^
```

**Comment by cvpe** [comment]
Old, in Python 2,  several problems Python 3, modernized, will be replaced

**Comment by cvpe** [comment]
Done

**Comment by cvpe** [comment]
Thanks for your patience and help
