### ISSUE TITLE
TabError in AddButtonsToPythonistaKeyboard

### ISSUE THREAD

**Issue by cclauss** [cvpe/Pythonista-scripts#32]
Python 3 refuses to guess what it means when both tabs and spaces are used to indent the same block of code.  Python 3 treats TabErrors as Syntax Errors.  The most automated way to fix TabErrors in Pythonista is to do __Reformat Code__ under the _wrench_ icon.  Or you can do it more manually if __Settings/Show Mixed Indentation__ is turned on.

From https://travis-ci.com/cvpe/Pythonista-scripts
```
./AddButtonsToPythonistaKeyboard.py:87:31: E999 TabError: inconsistent use of tabs and spaces in indentation
    		for pad_elem in self.pad:
                              ^
```

**Comment by cvpe** [comment]
One more time, my original code did not contain these errors. I don't know from where they come, sincerely.
Code remplaced

**Comment by cclauss** [comment]
From https://travis-ci.com/cvpe/Pythonista-scripts is now ✅

**Comment by cvpe** [comment]
🍾
