### ISSUE TITLE
Undefined name: 'f_full' in File_Explorer.py

### ISSUE THREAD

**Issue by cclauss** [cvpe/Pythonista-scripts#33]
This is the last file to fix...

We are adding to a variable that was not previously initialized.  The fix will be initialize the variable by adding the statement __f_full = “”__ somewhere before this line.

From https://travis-ci.com/cvpe/Pythonista-scripts
$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./File_Explorer.py:140:5: F821 undefined name 'f_full'
				f_full += file
    ^
1     F821 undefined name 'f_full'
1
```

**Comment by cvpe** [comment]
My original code contains
				f_full = file_path + file
I think the problem came when we updated the code everywhere by using +=

**Comment by cvpe** [comment]
Corrected, replaced
Thanks

**Comment by cvpe** [comment]
Never say "This is the last file to fix...".
Do we bet? 😀

**Comment by cvpe** [comment]
Are you in Swiss or USA? I see your last connection in Pythonista forum is 5h ago, late in Swiss! 😀
